### ISSUE TITLE
java.lang.AssertionError: 66

### ISSUE THREAD

**Issue by readme42** [Vektah/CodeGlance#117] opened 2016-05-23 13:30 UTC
Can't reproduce it, but it occured a few minutes ago:

```
java.lang.AssertionError: 66
    at com.intellij.openapi.editor.impl.IntervalTreeImpl$IntervalNode.computeDeltaUpToRoot(IntervalTreeImpl.java:221)
    at com.intellij.openapi.editor.impl.RangeMarkerImpl.getStartOffset(RangeMarkerImpl.java:88)
    at net.vektah.codeglance.render.Minimap.isFolded(Minimap.kt:200)
    at net.vektah.codeglance.render.Minimap.update(Minimap.kt:250)
    at net.vektah.codeglance.GlancePanel$updateImage$1.invoke(GlancePanel.kt:158)
    at net.vektah.codeglance.GlancePanel$updateImage$1.invoke(GlancePanel.kt:54)
    at net.vektah.codeglance.render.TaskRunner.run(TaskRunner.kt:46)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by arkuuu** [comment] 2016-06-02 08:04
I have a very similar error, only with `64` instead of `66`:

    java.lang.AssertionError: 64
	  at com.intellij.openapi.editor.impl.IntervalTreeImpl$IntervalNode.computeDeltaUpToRoot(IntervalTreeImpl.java:221)
	  at com.intellij.openapi.editor.impl.RangeMarkerImpl.getStartOffset(RangeMarkerImpl.java:88)
	  at net.vektah.codeglance.render.Minimap.isFolded(Minimap.kt:200)
	  at net.vektah.codeglance.render.Minimap.updateDimensions(Minimap.kt:68)
	  at net.vektah.codeglance.render.Minimap.update(Minimap.kt:219)
	  at net.vektah.codeglance.GlancePanel$updateImage$1.invoke(GlancePanel.kt:158)
	  at net.vektah.codeglance.GlancePanel$updateImage$1.invoke(GlancePanel.kt:54)
	  at net.vektah.codeglance.render.TaskRunner.run(TaskRunner.kt:46)
	  at java.lang.Thread.run(Thread.java:745)

Cannot reproduce. When it happened, I was creating a new task and changelist and thereby the editor closed all opened files.

**Comment by jimmywan** [comment] 2016-07-27 20:49
Duplicate of #112

**Closed** 2017-02-25 01:10 UTC
