### ISSUE TITLE
java.lang.AssertionError: 133

### ISSUE THREAD

**Issue by greenmarker** [Vektah/CodeGlance#120] opened 2016-06-15 08:06 UTC
IntelliJ Idea 2016.1.3
Windows 7

java.lang.AssertionError: 133
    at com.intellij.openapi.editor.impl.IntervalTreeImpl$IntervalNode.computeDeltaUpToRoot(IntervalTreeImpl.java:221)
    at com.intellij.openapi.editor.impl.RangeMarkerImpl.getStartOffset(RangeMarkerImpl.java:88)
    at net.vektah.codeglance.render.Minimap.isFolded(Minimap.kt:200)
    at net.vektah.codeglance.render.Minimap.update(Minimap.kt:267)
    at net.vektah.codeglance.GlancePanel$updateImage$1.invoke(GlancePanel.kt:158)
    at net.vektah.codeglance.GlancePanel$updateImage$1.invoke(GlancePanel.kt:54)
    at net.vektah.codeglance.render.TaskRunner.run(TaskRunner.kt:46)
    at java.lang.Thread.run(Thread.java:745)

**Comment by jimmywan** [comment] 2016-07-27 20:49
Duplicate of #112

**Closed** 2017-02-25 01:10 UTC
