### ISSUE TITLE
java.lang.AssertionError: 152

### ISSUE THREAD

**Issue by hm496** [Vektah/CodeGlance#172] opened 2017-03-23 02:01 UTC
152
java.lang.AssertionError: 152
	at com.intellij.openapi.editor.impl.IntervalTreeImpl$IntervalNode.computeDeltaUpToRoot(IntervalTreeImpl.java:225)
	at com.intellij.openapi.editor.impl.RangeMarkerImpl.getStartOffset(RangeMarkerImpl.java:86)
	at net.vektah.codeglance.render.Minimap.isFolded(Minimap.kt:199)
	at net.vektah.codeglance.render.Minimap.update(Minimap.kt:241)
	at net.vektah.codeglance.GlancePanel$updateImage$1.invoke(GlancePanel.kt:146)
	at net.vektah.codeglance.GlancePanel$updateImage$1.invoke(GlancePanel.kt:51)
	at net.vektah.codeglance.render.TaskRunner.run(TaskRunner.kt:46)
	at java.lang.Thread.run(Thread.java:745)

**Comment by Vektah** [comment] 2017-03-23 02:28
dupe of https://github.com/Vektah/CodeGlance/issues/171

**Closed by Vektah** 2017-03-23 02:28 UTC
