### ISSUE TITLE
Minimap is empty: java.lang.AssertionError: 84

### ISSUE THREAD

**Issue by TobseF** [Vektah/CodeGlance#169] opened 2017-03-14 13:24 UTC
After updating to the newest 1.5.1 the minimap is empty and an IDE exception occurs:

`java.lang.AssertionError: 84
	at com.intellij.openapi.editor.impl.IntervalTreeImpl$IntervalNode.computeDeltaUpToRoot(IntervalTreeImpl.java:221)
	at com.intellij.openapi.editor.impl.RangeMarkerImpl.getStartOffset(RangeMarkerImpl.java:88)
	at net.vektah.codeglance.render.Minimap.isFolded(Minimap.kt:199)
	at net.vektah.codeglance.render.Minimap.update(Minimap.kt:241)
	at net.vektah.codeglance.GlancePanel$updateImage$1.invoke(GlancePanel.kt:146)
	at net.vektah.codeglance.GlancePanel$updateImage$1.invoke(GlancePanel.kt:51)
	at net.vektah.codeglance.render.TaskRunner.run(TaskRunner.kt:46)
	at java.lang.Thread.run(Thread.java:745)`

**Platform:** Win + IntelliJ Ultimate 2016.3

**Comment by Vektah** [comment] 2017-03-23 02:28
Dupe of https://github.com/Vektah/CodeGlance/issues/171 (I know this was first but I've already started linking stuff to that one)

**Closed by Vektah** 2017-03-23 02:28 UTC
