### ISSUE TITLE
Text color in CodeGlance scroll area does not match editor color theme.

### ISSUE THREAD

**Issue by MonteCreasor** [Vektah/CodeGlance#114] opened 2016-03-25 15:58 UTC
My Android Studio 2.0 editor color scheme is "cobalt" but the CodeGlance scroll area displays what appears to be the default color scheme. Since I am used to my syntax coloring, this makes it harder to visually interpret the minimized text.

**Comment by StolenJelly** [comment] 2016-05-06 20:36
PHP Storm has the same issue, only selected coloring appears if at all and the issue is inconsistent across open files as some areas are all white while the same areas / code are correctly highlighted elsewhere.

**Comment by rogererens** [comment] 2016-12-01 15:04
@MonteCreasor: have you tried restarting the IDE? My guess is that CodeGlance uses the color scheme that is active at start up time.
When I change the color scheme of the IDE (PyCharm 2016.3 in my case) in File->Settings->Editor->Colors&Fonts, CodeGlance does not update its colors accordingly, making up for a confusing experience, indeed.

**Comment by Vektah** [comment] 2017-03-11 11:32
duplicate of https://github.com/Vektah/CodeGlance/issues/109

**Closed by Vektah** 2017-03-11 11:32 UTC
