### ISSUE TITLE
How to make CodeGlance bigger on large monitors

### ISSUE THREAD

**Issue by rootscript** [Vektah/CodeGlance#133] opened 2016-09-27 14:35 UTC
@Vektah Love this plugin, would love it more if there was an option to make the mini map larger.

I'm using CodeGlance in Webstorm on a large monitor, and having it twice the current maximum width would help the user to navigate code a lot more accurately on big screens.

Is there a setting (under the hood) somewhere? or can this become a Feature Request?

**Comment by andryushka** [comment] 2016-12-24 09:19
I have the same issue with 4k display, need way to increase plugin's font size.

**Comment by Vektah** [comment] 2017-03-11 11:25
Duplicate of https://github.com/Vektah/CodeGlance/issues/126

**Closed by Vektah** 2017-03-11 11:25 UTC
