### ISSUE TITLE
Allow to disable the resizing with mouse cursor

### ISSUE THREAD

**Issue by ksdev-pl** [Vektah/CodeGlance#175] opened 2017-03-24 20:28 UTC
Hi

Sometimes I accidentally click and resize the codeglance window. It would be great to have an option to disable the resizing with mouse cursor. We can set a precise width in options already. 

It's nothing critical, of course ;)

Thanks for your work!

**Comment by Vektah** [comment] 2017-03-26 03:55
Duplicate of https://github.com/Vektah/CodeGlance/issues/85

**Closed by Vektah** 2017-03-26 03:55 UTC
